language: csharp
mono: none
dotnet: 1.0.0-preview2-003121
script:
    - cd src/Avalanche
    - dotnet restore
    - dotnet build
    - cd ../../test/Avalanche.Tests
    - dotnet restore
    - dotnet build
    - dotnet test
    